# Generated by Django 3.2.6 on 2021-08-27 13:37

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[authentication.models.validate_email_domain, django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[authentication.models.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
